### ISSUE TITLE
Broken regex validation - Readme / Docs need update?

### ISSUE THREAD

**Issue by sebadob** [Keats/validator#325]
I was using validator v0.16 without any issues.  
I did not update to anything newer until now, because my compiler started yelling at me like crazy and I just did not have the time to deal with this.

I now decided to take a deeper look into what the issues are, and its mostly the regex validation that broke.

Just a short example, what I was doing with v0.16:

```rust
// the regex was defined somewhere else to be re-used in a lot of places, but that doesn't matter here
pub static RE_TEXT_1000: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"^[a-zA-Z0-9À-ÿ&.,_/()\s-]{0,1000}$").unwrap());

#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct MyValidatedStruct {
    #[validate(regex(path = "RE_TEXT_1000", code = "^[a-zA-Z0-9À-ÿ&.,_/()\\s-]{0,1000}$"))]
    pub text: String,
}
```

This breaks when I am trying to use any version past v0.16.
The compiler complains about `validator::validation::regex::AsRegex` not being implemented:

```
error[E0277]: the trait bound `once_cell::sync::Lazy<regex::Regex>: validator::validation::regex::AsRegex` is not satisfied
  --> common/src/api_types/timetracking/record.rs:7:48
   |
7  | #[derive(Debug, Clone, Serialize, Deserialize, Validate)]
   |                                                ^^^^^^^^ the trait `validator::validation::regex::AsRegex` is not implemented for `once_cell::sync::Lazy<regex::Regex>`, which is required by `&once_cell::sync::Lazy<regex::Regex>: validator::validation::regex::AsRegex`
   |
   = note: required for `&once_cell::sync::Lazy<regex::Regex>` to implement `validator::validation::regex::AsRegex`
note: required by a bound in `validate_regex`
  --> /home/sd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/validator-0.18.1/src/validation/regex.rs:57:42
   |
57 |     fn validate_regex(&self, regex: impl AsRegex) -> bool;
   |                                          ^^^^^^^ required by this bound in `ValidateRegex::validate_regex`
   = note: this error originates in the derive macro `Validate` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider dereferencing here
   |
17 |     #[validate(regex(path = *"RE_TEXT_1000"))]
   |                             +
```

The compiler hint with dereferencing is almost correct.
I can fix it with adding `*` inside the quotes like so:

```rust
#[validate(regex(path = "*RE_TEXT_1000"))]
```

Is this to be expected? If so, an update of readme and docs would probably be nice.

**Comment by Keats** [comment]
Thanks I've updated the README.

**Comment by tpoliaw** [comment]
As far as I can make out the `#[validate(regex = *RE_TWO_CHARS)]` form in the current version of the readme is still not working as expected. I'm getting `Unexpected type 'unary'`

**Comment by Keats** [comment]
Weird it's the same as in https://github.com/Keats/validator/blob/master/validator_derive_tests/tests/regex.rs
Can you try to make a failing test in that file?

**Comment by tpoliaw** [comment]
It looks like those tests all use the `#[validate(regex(path = *crate::RE2))]` form rather than `#[validate(regex = *crate::RE2)]`. I can add a failing test (and maybe look at a PR for a fix/to update the docs) but it won't be for a few days.

**Comment by Keats** [comment]
Oh I misread the SO question. It needs to be nested in parenthesis now afaik, i'll update the README
